INSERT INTO Countries VALUES (  1, 'Unknown');
INSERT INTO Countries VALUES (  2, 'Afghanistan');
INSERT INTO Countries VALUES (  3, 'Albania');
INSERT INTO Countries VALUES (  4, 'Algeria');
INSERT INTO Countries VALUES (  5, 'Andorra');
INSERT INTO Countries VALUES (  6, 'Angola');
INSERT INTO Countries VALUES (  7, 'Antigua and Barbuda');
INSERT INTO Countries VALUES (  8, 'Argentina');
INSERT INTO Countries VALUES (  9, 'Armenia');
INSERT INTO Countries VALUES ( 10, 'Australia');
INSERT INTO Countries VALUES ( 11, 'Austria');
INSERT INTO Countries VALUES ( 12, 'Azerbaijan');
INSERT INTO Countries VALUES ( 13, 'Bahamas');
INSERT INTO Countries VALUES ( 14, 'Bahrain');
INSERT INTO Countries VALUES ( 15, 'Bangladesh');
INSERT INTO Countries VALUES ( 16, 'Barbados');
INSERT INTO Countries VALUES ( 17, 'Belarus');
INSERT INTO Countries VALUES ( 18, 'Belgium');
INSERT INTO Countries VALUES ( 19, 'Belize');
INSERT INTO Countries VALUES ( 20, 'Benin');
INSERT INTO Countries VALUES ( 21, 'Bhutan');
INSERT INTO Countries VALUES ( 22, 'Bolivia');
INSERT INTO Countries VALUES ( 23, 'Bosnia and Herzegovina');
INSERT INTO Countries VALUES ( 24, 'Botswana');
INSERT INTO Countries VALUES ( 25, 'Brazil');
INSERT INTO Countries VALUES ( 26, 'Brunei ');
INSERT INTO Countries VALUES ( 27, 'Bulgaria');
INSERT INTO Countries VALUES ( 28, 'Burkina Faso');
INSERT INTO Countries VALUES ( 29, 'Burundi');
INSERT INTO Countries VALUES ( 30, 'Côte d''Ivoire');
INSERT INTO Countries VALUES ( 31, 'Cabo Verde');
INSERT INTO Countries VALUES ( 32, 'Cambodia');
INSERT INTO Countries VALUES ( 33, 'Cameroon');
INSERT INTO Countries VALUES ( 34, 'Canada');
INSERT INTO Countries VALUES ( 35, 'Central African Republic');
INSERT INTO Countries VALUES ( 36, 'Chad');
INSERT INTO Countries VALUES ( 37, 'Chile');
INSERT INTO Countries VALUES ( 38, 'China');
INSERT INTO Countries VALUES ( 39, 'Colombia');
INSERT INTO Countries VALUES ( 40, 'Comoros');
INSERT INTO Countries VALUES ( 41, 'Congo');
INSERT INTO Countries VALUES ( 42, 'Costa Rica');
INSERT INTO Countries VALUES ( 43, 'Croatia');
INSERT INTO Countries VALUES ( 44, 'Cuba');
INSERT INTO Countries VALUES ( 45, 'Cyprus');
INSERT INTO Countries VALUES ( 46, 'Czech Republic');
INSERT INTO Countries VALUES ( 47, 'Democratic Republic of the Congo');
INSERT INTO Countries VALUES ( 48, 'Denmark');
INSERT INTO Countries VALUES ( 49, 'Djibouti');
INSERT INTO Countries VALUES ( 50, 'Dominica');
INSERT INTO Countries VALUES ( 51, 'Dominican Republic');
INSERT INTO Countries VALUES ( 52, 'Ecuador');
INSERT INTO Countries VALUES ( 53, 'Egypt');
INSERT INTO Countries VALUES ( 54, 'El Salvador');
INSERT INTO Countries VALUES ( 55, 'Equatorial Guinea');
INSERT INTO Countries VALUES ( 56, 'Eritrea');
INSERT INTO Countries VALUES ( 57, 'Estonia');
INSERT INTO Countries VALUES ( 58, 'Eswatini');
INSERT INTO Countries VALUES ( 59, 'Ethiopia');
INSERT INTO Countries VALUES ( 60, 'Fiji');
INSERT INTO Countries VALUES ( 61, 'Finland');
INSERT INTO Countries VALUES ( 62, 'France');
INSERT INTO Countries VALUES ( 63, 'Gabon');
INSERT INTO Countries VALUES ( 64, 'Gambia');
INSERT INTO Countries VALUES ( 65, 'Georgia');
INSERT INTO Countries VALUES ( 66, 'Germany');
INSERT INTO Countries VALUES ( 67, 'Ghana');
INSERT INTO Countries VALUES ( 68, 'Greece');
INSERT INTO Countries VALUES ( 69, 'Grenada');
INSERT INTO Countries VALUES ( 70, 'Guatemala');
INSERT INTO Countries VALUES ( 71, 'Guinea');
INSERT INTO Countries VALUES ( 72, 'Guinea-Bissau');
INSERT INTO Countries VALUES ( 73, 'Guyana');
INSERT INTO Countries VALUES ( 74, 'Haiti');
INSERT INTO Countries VALUES ( 75, 'Holy See');
INSERT INTO Countries VALUES ( 76, 'Honduras');
INSERT INTO Countries VALUES ( 77, 'Hungary');
INSERT INTO Countries VALUES ( 78, 'Iceland');
INSERT INTO Countries VALUES ( 79, 'India');
INSERT INTO Countries VALUES ( 80, 'Indonesia');
INSERT INTO Countries VALUES ( 81, 'Iran');
INSERT INTO Countries VALUES ( 82, 'Iraq');
INSERT INTO Countries VALUES ( 83, 'Ireland');
INSERT INTO Countries VALUES ( 84, 'Israel');
INSERT INTO Countries VALUES ( 85, 'Italy');
INSERT INTO Countries VALUES ( 86, 'Jamaica');
INSERT INTO Countries VALUES ( 87, 'Japan');
INSERT INTO Countries VALUES ( 88, 'Jordan');
INSERT INTO Countries VALUES ( 89, 'Kazakhstan');
INSERT INTO Countries VALUES ( 90, 'Kenya');
INSERT INTO Countries VALUES ( 91, 'Kiribati');
INSERT INTO Countries VALUES ( 92, 'Kuwait');
INSERT INTO Countries VALUES ( 93, 'Kyrgyzstan');
INSERT INTO Countries VALUES ( 94, 'Laos');
INSERT INTO Countries VALUES ( 95, 'Latvia');
INSERT INTO Countries VALUES ( 96, 'Lebanon');
INSERT INTO Countries VALUES ( 97, 'Lesotho');
INSERT INTO Countries VALUES ( 98, 'Liberia');
INSERT INTO Countries VALUES ( 99, 'Libya');
INSERT INTO Countries VALUES (100, 'Liechtenstein');
INSERT INTO Countries VALUES (101, 'Lithuania');
INSERT INTO Countries VALUES (102, 'Luxembourg');
INSERT INTO Countries VALUES (103, 'Madagascar');
INSERT INTO Countries VALUES (104, 'Malawi');
INSERT INTO Countries VALUES (105, 'Malaysia');
INSERT INTO Countries VALUES (106, 'Maldives');
INSERT INTO Countries VALUES (107, 'Mali');
INSERT INTO Countries VALUES (108, 'Malta');
INSERT INTO Countries VALUES (109, 'Marshall Islands');
INSERT INTO Countries VALUES (110, 'Mauritania');
INSERT INTO Countries VALUES (111, 'Mauritius');
INSERT INTO Countries VALUES (112, 'Mexico');
INSERT INTO Countries VALUES (113, 'Micronesia');
INSERT INTO Countries VALUES (114, 'Moldova');
INSERT INTO Countries VALUES (115, 'Monaco');
INSERT INTO Countries VALUES (116, 'Mongolia');
INSERT INTO Countries VALUES (117, 'Montenegro');
INSERT INTO Countries VALUES (118, 'Morocco');
INSERT INTO Countries VALUES (119, 'Mozambique');
INSERT INTO Countries VALUES (120, 'Myanmar');
INSERT INTO Countries VALUES (121, 'Namibia');
INSERT INTO Countries VALUES (122, 'Nauru');
INSERT INTO Countries VALUES (123, 'Nepal');
INSERT INTO Countries VALUES (124, 'Netherlands');
INSERT INTO Countries VALUES (125, 'New Zealand');
INSERT INTO Countries VALUES (126, 'Nicaragua');
INSERT INTO Countries VALUES (127, 'Niger');
INSERT INTO Countries VALUES (128, 'Nigeria');
INSERT INTO Countries VALUES (129, 'North Korea');
INSERT INTO Countries VALUES (130, 'North Macedonia');
INSERT INTO Countries VALUES (131, 'Norway');
INSERT INTO Countries VALUES (132, 'Oman');
INSERT INTO Countries VALUES (133, 'Pakistan');
INSERT INTO Countries VALUES (134, 'Palau');
INSERT INTO Countries VALUES (135, 'Palestine State');
INSERT INTO Countries VALUES (136, 'Panama');
INSERT INTO Countries VALUES (137, 'Papua New Guinea');
INSERT INTO Countries VALUES (138, 'Paraguay');
INSERT INTO Countries VALUES (139, 'Peru');
INSERT INTO Countries VALUES (140, 'Philippines');
INSERT INTO Countries VALUES (141, 'Poland');
INSERT INTO Countries VALUES (142, 'Portugal');
INSERT INTO Countries VALUES (143, 'Qatar');
INSERT INTO Countries VALUES (144, 'Romania');
INSERT INTO Countries VALUES (145, 'Russia');
INSERT INTO Countries VALUES (146, 'Rwanda');
INSERT INTO Countries VALUES (147, 'Saint Kitts and Nevis');
INSERT INTO Countries VALUES (148, 'Saint Lucia');
INSERT INTO Countries VALUES (149, 'Saint Vincent and the Grenadines');
INSERT INTO Countries VALUES (150, 'Samoa');
INSERT INTO Countries VALUES (151, 'San Marino');
INSERT INTO Countries VALUES (152, 'Sao Tome and Principe');
INSERT INTO Countries VALUES (153, 'Saudi Arabia');
INSERT INTO Countries VALUES (154, 'Senegal');
INSERT INTO Countries VALUES (155, 'Serbia');
INSERT INTO Countries VALUES (156, 'Seychelles');
INSERT INTO Countries VALUES (157, 'Sierra Leone');
INSERT INTO Countries VALUES (158, 'Singapore');
INSERT INTO Countries VALUES (159, 'Slovakia');
INSERT INTO Countries VALUES (160, 'Slovenia');
INSERT INTO Countries VALUES (161, 'Solomon Islands');
INSERT INTO Countries VALUES (162, 'Somalia');
INSERT INTO Countries VALUES (163, 'South Africa');
INSERT INTO Countries VALUES (164, 'South Korea');
INSERT INTO Countries VALUES (165, 'South Sudan');
INSERT INTO Countries VALUES (166, 'Spain');
INSERT INTO Countries VALUES (167, 'Sri Lanka');
INSERT INTO Countries VALUES (168, 'Sudan');
INSERT INTO Countries VALUES (169, 'Suriname');
INSERT INTO Countries VALUES (170, 'Sweden');
INSERT INTO Countries VALUES (171, 'Switzerland');
INSERT INTO Countries VALUES (172, 'Syria');
INSERT INTO Countries VALUES (173, 'Tajikistan');
INSERT INTO Countries VALUES (174, 'Tanzania');
INSERT INTO Countries VALUES (175, 'Thailand');
INSERT INTO Countries VALUES (176, 'Timor-Leste');
INSERT INTO Countries VALUES (177, 'Togo');
INSERT INTO Countries VALUES (178, 'Tonga');
INSERT INTO Countries VALUES (179, 'Trinidad and Tobago');
INSERT INTO Countries VALUES (180, 'Tunisia');
INSERT INTO Countries VALUES (181, 'Turkey');
INSERT INTO Countries VALUES (182, 'Turkmenistan');
INSERT INTO Countries VALUES (183, 'Tuvalu');
INSERT INTO Countries VALUES (184, 'Uganda');
INSERT INTO Countries VALUES (185, 'Ukraine');
INSERT INTO Countries VALUES (186, 'United Arab Emirates');
INSERT INTO Countries VALUES (187, 'United Kingdom');
INSERT INTO Countries VALUES (188, 'United States of America');
INSERT INTO Countries VALUES (189, 'Uruguay');
INSERT INTO Countries VALUES (190, 'Uzbekistan');
INSERT INTO Countries VALUES (191, 'Vanuatu');
INSERT INTO Countries VALUES (192, 'Venezuela');
INSERT INTO Countries VALUES (193, 'Vietnam');
INSERT INTO Countries VALUES (194, 'Yemen');
INSERT INTO Countries VALUES (195, 'Zambia');
INSERT INTO Countries VALUES (196, 'Zimbabwe');

INSERT INTO DietaryTags VALUES (1, 'Vegetarian');
INSERT INTO DietaryTags VALUES (2, 'Vegan');
INSERT INTO DietaryTags VALUES (3, 'Pescetarian');
INSERT INTO DietaryTags VALUES (4, 'Kosher');
INSERT INTO DietaryTags VALUES (5, 'Halal');

INSERT INTO MondialMunchEvents VALUES (1, 'Silk Road Event!', TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-06-01', 'YYYY-MM-DD'), 'The Silk Road was a series of routes  used for trade between Europe and Asia between the 2nd century BCE until the 15th. It spans ~6,500 kilometers and it played a central role in joining the East and West culturally, economically and religiously. To celebrate this major part of history, the Mondial Munch monthly event this month is to make one recipe from every country on the silk road! Track your progress below and good luck!');

INSERT INTO CountryMondialMunchEvent(78, 1); --Italy
INSERT INTO CountryMondialMunchEvent(62, 1); --Greece
INSERT INTO CountryMondialMunchEvent(166, 1); --Turkey
INSERT INTO CountryMondialMunchEvent(74, 1); --Iran
INSERT INTO CountryMondialMunchEvent(72, 1); --India
INSERT INTO CountryMondialMunchEvent(32, 1); --China
INSERT INTO CountryMondialMunchEvent(157, 1); --Syria
INSERT INTO CountryMondialMunchEvent(88, 1); --Lebanon
INSERT INTO CountryMondialMunchEvent(81, 1); --Jordan
INSERT INTO CountryMondialMunchEvent(77, 1); --Israel


INSERT INTO MondialMunchEvents VALUES (2, 'Banana Republic Week!', TO_DATE('2024-05-11', 'YYYY-MM-DD'), TO_DATE('2024-05-25', 'YYYY-MM-DD'), 'The banana republics were (in some cases still are) politaclly and economically unstable countries where the government is in part or totally controlled by a private for-profit company, making the country an asset for the profit of its ruling class. Some of these countries are being featured here as the Mondial Munch bi-weekly event to bring help bring some awareness to these regimes. Track your progress below and consider reading up some of the history of these countries.');

INSERT INTO CountryMondialMunchEvent(69, 2); --Honduras
INSERT INTO CountryMondialMunchEvent(64, 2); --Guatemala
INSERT INTO CountryMondialMunchEvent(36, 2); --Costa Rica
INSERT INTO CountryMondialMunchEvent(122, 2); --Panama
INSERT INTO CountryMondialMunchEvent(39, 2); --Cuba
